### ISSUE TITLE
Fails to create folder with special characters

### ISSUE THREAD

**Issue by Cronus89** [rcarmo/imapbackup#12]
The email server is surgemail, and has a semi invisible System Recycling Folder.  You only typically see it when using IMAP.

I get the below error when it tries to create this folder. I assume it doesnt like a character somewhere

>Finding Folders: 62 folders
Traceback (most recent call last):
File "/mnt/user/backups/email/imapbackup/imapbackup.py", line 749, in
main()
File "/mnt/user/backups/email/imapbackup/imapbackup.py", line 648, in main
create_folder_structure(names)
File "/mnt/user/backups/email/imapbackup/imapbackup.py", line 626, in create_folder_structure
os.mkdir(disk_foldername)
OSError: [Errno 2] No such file or directory: '-System Recycling-.sbd/#Lists.sbd'

**Comment by rcarmo** [comment]
Strange. None of those characters is by itself forbidden in a UNIX filesystem. Have you tried using `--folders` to work around that, or creating a non-Thunderbird mailbox?

**Comment by Cronus89** [comment]
Seems to be working with non thunderbird style.  Whats the difference?

Also i wasnt going to do --folders as if there are folders added later, I'd like them to automatically be backed up. an exclude option might be handy.

**Comment by rcarmo** [comment]
This has been open for a few months now with no activity, so I'm closing it.
